In [1]:
from pathlib import Path
import torch
import torch.nn as nn
from config import get_config, get_weights_file_path
from train import get_model, get_ds_csv, run_validation
from train import translate_input_string, translate_input_string_alt, eos_add, translate_input_string_test

C:\Users\oscar\AppData\Roaming\Python\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\oscar\AppData\Roaming\Python\Python311\site-packages\torchaudio\backend\utils.py:74: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")


In [2]:
# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)
config = get_config()
# config['model_basename'] = "tmodel_eight_four_id_"
config['model_basename'] = "tmodel_eight_four_"
# Training bahasa target menjadi bahasa Maanyan
# config['lang_src'] = "Indonesia"
# config['lang_tgt'] = "Maanyan"
train_dataloader, val_dataloader, tokenizer_src, tokenizer_tgt = get_ds_csv(config)
model = get_model(config, tokenizer_src.get_vocab_size(), tokenizer_tgt.get_vocab_size()).to(device)

# Load the pretrained weights
model_filename = get_weights_file_path(config, f"60")
state = torch.load(model_filename)
model.load_state_dict(state['model_state_dict'])

Using device: cuda
Max length of source sentence: 22
Max length of target sentence: 24


<All keys matched successfully>

In [3]:
input_string = "hanyu"

translation = translate_input_string_test(model, input_string, tokenizer_src, tokenizer_tgt, config['seq_len'], device)


[7]
encoder_mask
tensor([[[[1]]]], device='cuda:0')
tensor([[[-1.4840e+00, -7.9772e-01, -7.4627e-01, -5.3501e-01,  3.2536e-01,
           1.4295e+00,  9.3916e-01,  5.8246e-01,  1.1872e+00,  2.1721e-01,
           6.9799e-01, -5.4849e-01,  8.8906e-01,  9.4425e-01,  9.6896e-01,
           4.5645e-01,  4.4833e-01, -2.2724e-02, -6.3422e-01,  6.2707e-01,
          -1.1297e-01,  1.3653e+00,  1.7171e+00, -4.0687e-01, -2.4331e+00,
           2.2592e-01, -7.0665e-01,  1.4628e+00,  4.6239e-02,  1.8869e+00,
           2.2283e-01,  7.8112e-03,  1.1667e+00, -7.4777e-01, -1.0916e+00,
          -5.5236e-01,  1.6790e+00,  7.9127e-01,  7.5545e-01, -1.2387e+00,
          -4.5585e-01, -3.2565e-01, -7.2965e-01,  1.3799e+00,  7.9528e-01,
          -2.3613e-01, -1.4368e+00, -1.4632e-01, -2.0903e+00, -1.4042e-01,
           6.0188e-01,  2.2229e+00,  7.0592e-01, -5.2225e-01,  6.4666e-01,
          -9.8753e-01, -2.5090e+00, -3.8189e-01,  1.2537e+00,  1.8164e+00,
           3.1610e-02, -8.2459e-02,  2.2661e-01,

In [4]:
input_string = "hanyu"

# input_string = eos_add(input_string)

# print(input_string)
translation = translate_input_string(model, input_string, tokenizer_src, tokenizer_tgt, config['seq_len'], device)
print(f"Input String    : '{input_string}'")
print(f"Translation     : '{translation}'")

tensor([[[-1.4840e+00, -7.9772e-01, -7.4627e-01, -5.3501e-01,  3.2536e-01,
           1.4295e+00,  9.3916e-01,  5.8246e-01,  1.1872e+00,  2.1721e-01,
           6.9799e-01, -5.4849e-01,  8.8906e-01,  9.4425e-01,  9.6896e-01,
           4.5645e-01,  4.4833e-01, -2.2724e-02, -6.3422e-01,  6.2707e-01,
          -1.1297e-01,  1.3653e+00,  1.7171e+00, -4.0687e-01, -2.4331e+00,
           2.2592e-01, -7.0665e-01,  1.4628e+00,  4.6239e-02,  1.8869e+00,
           2.2283e-01,  7.8112e-03,  1.1667e+00, -7.4777e-01, -1.0916e+00,
          -5.5236e-01,  1.6790e+00,  7.9127e-01,  7.5545e-01, -1.2387e+00,
          -4.5585e-01, -3.2565e-01, -7.2965e-01,  1.3799e+00,  7.9528e-01,
          -2.3613e-01, -1.4368e+00, -1.4632e-01, -2.0903e+00, -1.4042e-01,
           6.0188e-01,  2.2229e+00,  7.0592e-01, -5.2225e-01,  6.4666e-01,
          -9.8753e-01, -2.5090e+00, -3.8189e-01,  1.2537e+00,  1.8164e+00,
           3.1610e-02, -8.2459e-02,  2.2661e-01,  6.9827e-01, -1.9903e+00,
          -2.2863e+00,  8

In [99]:
def add_eos(string):
    return ""+ string + ""

# Menggunakan fungsi translate_input_string

# input_string = add_eos("aku") 
input_string = ["aku makan durian kamu", "mulek", "aku terkejut"]
output_string = ["hayu naun hawi ma ina", "pulang", 'embah aku']
translation = translate_input_string(model, input_string[0], tokenizer_src, tokenizer_tgt, config['seq_len'], device)
print(f"Input String    : '{input_string[0]}'")
print(f"Output String   : '{output_string[0]}'")
print(f"Translation     : '{translation}'")
print('===============================================')
translation = translate_input_string(model, input_string[1], tokenizer_src, tokenizer_tgt, config['seq_len'], device)
print(f"Input String    : '{input_string[1]}'")
print(f"Output String   : '{output_string[1]}'")
print(f"Translation     : '{translation}'")
print('===============================================')
translation = translate_input_string(model, input_string[2], tokenizer_src, tokenizer_tgt, config['seq_len'], device)
print(f"Input String    : '{input_string[2]}'")
print(f"Output String   : '{output_string[2]}'")
print(f"Translation     : '{translation}'")

Input String    : 'aku makan durian kamu'
Output String   : 'hayu naun hawi ma ina'
Translation     : 'aku andri hanyu nguta ruyan'
Input String    : 'mulek'
Output String   : 'pulang'
Translation     : ''
Input String    : 'aku terkejut'
Output String   : 'embah aku'
Translation     : 'aku'


In [4]:
jika = "kamu makan."

print(eos_add(jika))

kamu makan [EOS]


In [113]:
from nltk.translate.bleu_score import sentence_bleu

In [134]:
reference = [['aku', 'makan', 'durian' ],['kamu', 'makan', 'durian']]


input_string = 'hanyu puang nguta ruyan ina'

test = translate_input_string(model, input_string, tokenizer_src, tokenizer_tgt, config['seq_len'], device)
score = sentence_bleu(reference, test.split(), weights=(1, 0, 0, 0))
print(score)

0.42857142857142855


In [121]:

reference = [['aku', 'nguta', 'ruyan' ],['hanyu', 'nguta', 'ruyan']]


input_string = 'aku makan durian ke sini'

test = translate_input_string(model, input_string, tokenizer_src, tokenizer_tgt, config['seq_len'], device)
score = sentence_bleu(reference, test.split(), weights=(0.25, 0.25, 0, 0))
print(score)

0.6389431042462724


In [4]:
run_validation(model, val_dataloader, tokenizer_src, tokenizer_tgt, config['seq_len'], device, lambda msg: print(msg), 0, None, num_examples=10)

--------------------------------------------------------------------------------
    SOURCE: ma wuang tangan tuanku hanye haut nyarah kawan anak murunsia hang awe awe here muneng
    TARGET: ke dalam tangan tuanku ia telah menyerahkan anak-anak manusia di mana pun mereka berada
 PREDICTED: ke dalam tuanku ia telah anak - anak manusia di mana pun mereka
--------------------------------------------------------------------------------
    SOURCE: bana yiru puang tau na ari
    TARGET: benda itu tidak dapat dijual
 PREDICTED: itu tidak dapat
--------------------------------------------------------------------------------
    SOURCE: balalu siwui riwut mitah jendela
    TARGET: lalu angin mengembuskannya melalui jendela
 PREDICTED: lalu
--------------------------------------------------------------------------------
    SOURCE: palus midi hanye jari panguasa ma katuluh wilayah babel nelang kapala katuluh ulun marahati hang babel
    TARGET: serta menjadikannya penguasa atas seluruh wilayah 